if OBJECT_ID('MIGRATION_DATA') is null
BEGIN
    CREATE TABLE MIGRATION_DATA (
        LAST_RUN VARCHAR(100),
        LAST_MIGRATION_NAME VARCHAR(1000)
    )
    INSERT INTO MIGRATION_DATA VALUES (NULL, NULL);
END