CREATE LOGIN [lastm] WITH PASSWORD=N'lastm', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [securityadmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [serveradmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [setupadmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [processadmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [diskadmin] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [dbcreator] ADD MEMBER [lastm]
GO

ALTER SERVER ROLE [bulkadmin] ADD MEMBER [lastm]
GO

CREATE DATABASE last_minute
GO

USE last_minute
GO

CREATE TABLE EXAMPLE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NUME VARCHAR(100) NULL
)

GO

INSERT INTO EXAMPLE (NUME) VALUES
('BOGDAN'), ('MIHAI'), ('IOAN')